[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyciters"
# dynamic = ["version"] 
version = "0.1" 
description = 'A simple utility for converting USDA ERS publication ids or urls into bibtex entries'
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
keywords = []
authors = [
  { name = "Dylan Turner", email = "dylan.turner3@outlook.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]
dependencies = []

[project.urls]
Documentation = "https://github.com/dylan-turner25/pyciters#readme"
Issues = "https://github.com/dylan-turner25/pyciters/issues"
Source = "https://github.com/dylan-turner25/pyciters"

#[tool.hatch.version]
#path = "src/pyciters/__about__.py"
